### ISSUE TITLE
Update Documentation/Readme

### ISSUE THREAD

**Issue by josephecombs** [thegengen/cloudprint#14]
Google's documentation for cloudprint is really old now.  Their [API playground](https://developers.google.com/oauthplayground/) does not feature it any longer, rather they have a ...minimal... simulation tool [here](https://www.google.com/cloudprint/simulate.html)

Also, using this gem before the point of having a refresh_token is impossible, and understanding the flow of obtaining a refresh_token is complicated.  Martin Fowler [wrote an article about this](http://martinfowler.com/articles/command-line-google.html), and he was using a well-documented API!

**Comment by thegengen** [comment]
I agree with both statements. As for #2, I do intend to provide a more automated workflow up to the point of getting a refresh token. Unfortunately, I don't have much time to work on the CloudPrint gem.

If you feel this is something you'd like to tackle, I think I can provide some guidance for it.
