### ISSUE TITLE
Make gem more powerful

### ISSUE THREAD

**Issue by josephecombs** [thegengen/cloudprint#15]
The Cloudprint API can do a lot more stuff than what is currently in this gem.  A list of capabilities (most of which I don't understand) are here:

https://www.google.com/cloudprint/simulate.html

**Comment by thegengen** [comment]
I agree, and I'm always open to PRs that add more functionality. Also, if you have specific functionality that you want me to add, I'll try to make time for it.

I'm going to close this ticket for now. Feel free to open others (and other PRs) on a per case basis.
