### ISSUE TITLE
client.auth method does not exist

### ISSUE THREAD

**Issue by nileshtrivedi** [thegengen/cloudprint#19]
I am using gem version 0.3.2 which is also the latest version in the repo. The README says that I should call client.auth.generate_url method. However, I get the following error:

NoMethodError: undefined method `auth' for #<CloudPrint::Client:0x007f9559098918>

It seems like, either a new gem version needs to be pushed to rubygems.org or the documentation is out of date.

**Comment by jimryan** [comment]
You're reading the README from master, when you should be reading the README from the version of the gem you're running.  

https://github.com/thegengen/cloudprint/blob/v0.3.2/README.md
