### ISSUE TITLE
undefined method `auth`

### ISSUE THREAD

**Issue by tgonl** [thegengen/cloudprint#20]
Why can't we access the `auth` method when initialising `CloudPrint::Client.new` ?

**Comment by jimryan** [comment]
Are you running the gem from master or one of the released versions?

**Comment by tgonl** [comment]
I have this on my `Gemfile`

```
gem 'cloudprint', git: 'https://github.com/thegengen/cloudprint.git', branch: 'master'
```

Already checked the gem folder, can't find the `auth.rb` file.

**Comment by tgonl** [comment]
The `auth` method is also missing from the `client.rb` file.

**Comment by tgonl** [comment]
Ok, deleted everything, looks like it's working now. Cheers anyway 👍

**Comment by jimryan** [comment]
Glad you got it working
