### ISSUE TITLE
Can't print PDF google drive

### ISSUE THREAD

**Issue by tmedford** [thegengen/cloudprint#24]
Can't get pdf to correctly print when printing to google drive. pdf shows up fine on local but comes across blank in google drive. 
    File.open(Rails.root.join('public', "#{invoice_number}.pdf"), 'wb') do |file|
       file.write(decoded_invoice_pdf)
     end
     printer.print(title: "#{invoice_number}_1.pdf", content: decoded_invoice_pdf, content_type: "application/pdf")
    printer.print(title: "#{invoice_number}_2.pdf", content: File.read(Rails.root.join('public', "#{invoice_number}.pdf")), content_type: "application/pdf")

**Comment by thegengen** [comment]
Hi. Unfortunately, I won't be able to get to this until the middle of next week. In the meantime, if you could share a version of the PDF with all the sensitive info removed, either here or via email, that could be very useful.

**Comment by thegengen** [comment]
Hi again, @tmedford. I need to see what it is you're trying to print if I'm to do anything about this ticket.

**Comment by troelskn** [comment]
I have the same issue. I've tried to send a bunch of different pdfs. They all end up blank. Curiously, they have the right number of pages. I tried downloading the resulting file and it resembles in size but is clearly different. I think Google Drive is being clever and tries to convert the document TO pdf, even though it is already on this form.

**Comment by troelskn** [comment]
After some digging around, I managed to figure out the problem. If you just pass a pdf as a string, a request using `application/x-www-form-urlencoded` will be constructed. Apparently something on the server side chokes on that somehow (Even though I can't find any mention of that in Google's documentation). If, instead, the contents are written to a file or wrapped in a StringIO, the request is built with `multipart/form-data` and it works.

I think we should either always use multipart in `CloudPrint::Printer#print` or it should be clearly documented in the read-me. Any thoughts on this @thegengen ?
